server:
  port: 8088
#  servlet:
#    context-path: /smbms

## 数据源配置
spring:
  datasource:
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_smbms?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  ## freemarker
  freemarker:
    suffix: .ftl
    content-type: text/html
    charset: UTF-8
    template-loader-path: classpath:/views/
    ## 热部署配置
  devtools:
    restart:
      enabled: true
      # 设置重启的目录，添加目录的文件需要restart
      additional-paths: src/main/java
      # 解决项目自动重新编译后接口报404的问题
      poll-interval: 3000
      quiet-period: 1000
#  cache:
#    ehcache:
#      config: classpath:ehcahe.xml

## mybatis 配置A
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.xxxx.springboot.vo
  configuration:
    ## 下划线转驼峰配置
    map-underscore-to-camel-case: true
## pageHelper
pagehelper:
  helper-dialect: mysql

#显示dao 执行sql语句
logging:
  level:
    com:
      smbms:
        dao: debug
